name: "Terraform Destroy"

on:
  workflow_dispatch: # 🎛️ Manual teardown switch triggered exclusively by your click!

permissions:
  contents: read

jobs:
  terraform_destroy:
    name: "Execute Automated Live Cloud Teardown"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform Engine"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.2"

      - name: "Initialize S3 Remote Backend"
        run: terraform init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Generate Destruction Forecast Plan"
        run: terraform plan -destroy -out=destroy.tfplan -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Execute Saved Destruction Plan"
        run: terraform apply -input=false -auto-approve destroy.tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

